### PR TITLE
Video fixes

### PR DESCRIPTION
**Pull request by paulb-nl**
* Fix hires ce_pix
* 1 black pixel column on the left and 1 pixel missing on the right
* Missing last line
* Original 55Hz timing with option for PAL
* Add Analog H/V offset options

### CODE REVIEW

**Comment by alanswx** [comment]
Have you noticed the bricks in mode runner are missing lines until a reset? Have you looked at that?

**Comment by paulb-nl** [comment]
That was caused by the async ce_pix divider which was always dividing by 8 which is not correct for hires games. A reset would change the phase between the divider and the core's pixel clock so different pixels would be skipped everytime after a reset.

I have changed it to generate a ce_pix on the falling edge of the core's pixel clock so it is always synced at the correct cycle. Async dividers shouldn't be used.

**Comment by alanswx** [comment]
Did you mean to close this? Thank you for explaining the fix. Exciting. That has been bothering me for a while.

**Comment by paulb-nl** [comment]
Yea I saw a typo that I am fixing

**Comment by paulb-nl** [comment]
Should be good now

**Comment by JimmyStones** [comment]
@paulb-nl just released your changes - it looks so much better!

**Comment by paulb-nl** [comment]
Yeah a lot of pixels were missing in hires mode 😃

**Pull request merged**
